// API Routes
export const EQUIPMENTS_API_ROUTE = 'equipment';
export const GET_EQUIPMENTS_API_ROUTE = EQUIPMENTS_API_ROUTE;
export const GET_POWERON_EQUIPMENTS_API_ROUTE = `${EQUIPMENTS_API_ROUTE}/poweron`;
export const GET_POWEROFF_EQUIPMENTS_API_ROUTE = `${EQUIPMENTS_API_ROUTE}/poweroff`;
